### ISSUE TITLE
`grow_space()` panics for Dacapo Chopin lusearch

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#421] opened 2021-08-24 15:56 UTC
Running dacapo chopin lusearch in fastdebug build, it seems like (when using a plan that uses the LargeObjectSpace such as Immix, SemiSpace, or GenCopy) an allocation to the LargeObjectSpace panics in `grow_space()` with:

```
$ RUST_BACKTRACE=1 MMTK_PLAN=SemiSpace ~/git/mmtk-openjdk/repos/openjdk/build/linux-x86_64-normal-server-fastdebug/jdk/bin/java -XX:+UseThirdPartyHeap -Xms128M -Xmx128M -jar /usr/share/benchmarks/dacapo/dacapo-evaluation-git-69a704e.jar lusearch
[2021-08-24T15:05:36Z INFO  mmtk::memory_manager] Initialized MMTk with SemiSpace
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, in a possible range of [1,2048]
[2021-08-24T15:12:17Z INFO  mmtk::plan::global]   [POLL] los: Triggering collection
[2021-08-24T15:12:17Z INFO  mmtk::scheduler::gc_work] End of GC
[2021-08-24T15:12:18Z INFO  mmtk::plan::global] User triggering collection
[2021-08-24T15:12:18Z INFO  mmtk::scheduler::gc_work] End of GC
===== DaCapo evaluation-git-69a704e lusearch starting =====
thread '<unnamed>' panicked at 'Tried to grow space from 0x80104c01000 for 131072 bytes: should only grow space for new chunks at chunk-aligned start address', /home/kunals/git/mmtk-core/src/policy/space.rs:358:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/std/src/panicking.rs:460:5
   2: mmtk::policy::space::Space::grow_space
             at /home/kunals/git/mmtk-core/src/policy/space.rs:358:9
   3: mmtk::policy::space::Space::acquire
             at /home/kunals/git/mmtk-core/src/policy/space.rs:289:21
   4: mmtk::policy::largeobjectspace::LargeObjectSpace<VM>::allocate_pages
             at /home/kunals/git/mmtk-core/src/policy/largeobjectspace.rs:219:9
   5: <mmtk::util::alloc::large_object_allocator::LargeObjectAllocator<VM> as mmtk::util::alloc::allocator::Allocator<VM>>::alloc_slow_once
             at /home/kunals/git/mmtk-core/src/util/alloc/large_object_allocator.rs:43:18
   6: mmtk::util::alloc::allocator::Allocator::alloc_slow_inline
             at /home/kunals/git/mmtk-core/src/util/alloc/allocator.rs:132:26
   7: <mmtk::util::alloc::large_object_allocator::LargeObjectAllocator<VM> as mmtk::util::alloc::allocator::Allocator<VM>>::alloc_slow
             at /home/kunals/git/mmtk-core/src/util/alloc/large_object_allocator.rs:35:9
   8: <mmtk::util::alloc::large_object_allocator::LargeObjectAllocator<VM> as mmtk::util::alloc::allocator::Allocator<VM>>::alloc
             at /home/kunals/git/mmtk-core/src/util/alloc/large_object_allocator.rs:30:29
   9: <mmtk::plan::mutator_context::Mutator<VM> as mmtk::plan::mutator_context::MutatorContext<VM>>::alloc
             at /home/kunals/git/mmtk-core/src/plan/mutator_context.rs:66:9
  10: mmtk::memory_manager::alloc
             at /home/kunals/git/mmtk-core/src/memory_manager.rs:130:5
  11: alloc
             at /home/kunals/git/mmtk-openjdk/mmtk/src/api.rs:86:5
  12: _ZN18MMTkMutatorContext5allocEm9Allocator
  13: _ZN8MMTkHeap12mem_allocateEmPb
  14: _ZNK12MemAllocator8allocateEv
  15: _ZN13CollectedHeap14array_allocateEP5KlassiibP6Thread
  16: _ZN14TypeArrayKlass15allocate_commonEibP6Thread
  17: _ZN10oopFactory13new_typeArrayE9BasicTypeiP6Thread
  18: _ZN8Runtime114new_type_arrayEP10JavaThreadP5Klassi
  19: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
zsh: abort (core dumped)  RUST_BACKTRACE=1 MMTK_PLAN=SemiSpace  -XX:+UseThirdPartyHeap -Xms128M -Xmx128
```

With my informal testing, it seems like lusearch did not panic with [this commit in mmtk-core](https://github.com/mmtk/mmtk-core/commit/5d6761b25699098dd96e4f45887894f63b682440) and [this commit in mmtk-openjdk](https://github.com/mmtk/mmtk-openjdk/commit/3545d16504b0602885a9f23f33537153d67ad3d8). However the commits not panicking makes sense as LOS was not being used before.

Unfortunately these commits still encounter the same NPE and Lucene parser exception as before (see #423). In fact this error seems to have been present at least since the 0.4 release (furthest I went back to check) of mmtk-core and mmtk-openjdk.

**Comment by qinsoon** [comment] 2021-10-17 22:19
This is a duplicate of https://github.com/mmtk/mmtk-core/issues/374. Also this assertion has been removed. I am closing this.

**Closed by qinsoon** 2021-10-17 22:19 UTC
Labels: C-bug, A-allocator
