### ISSUE TITLE
Remove `cast_ref_to_mut` related to SFT

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#851] opened 2023-06-08 06:16 UTC
Parent: https://github.com/mmtk/mmtk-core/issues/850

SFTMap implementations cast `&self` to `&mut self` for modifying its underlying `sft: Vec<&'a (dyn SFT + Sync + 'static)>`.  This table is accessed by multiple threads, but it needs to be updated occasionally.  It is problematic in two ways:

1.  Each element can be read and updated at the same time.  This is a data race which has undefined behaviour.
2.  After one thread grows the space, other threads can access the SFT for the extended part while the space that grew the space is still updating the SFT entries.  See: https://github.com/mmtk/mmtk-core/blob/f1a0bb7fbec97dd84e35a40e8be01cf5018f2f9e/src/policy/space.rs#L81

One way to solve the first problem is changing the elements of the `Vec` to `AtomicPtr`.  However, `& dyn Trait` is 16 bytes in size.

The "double-checked locking" algorithm can be used for data structures that are lazily initialised.  I think the use pattern of SFT matches lazy initialisation in certain ways, and may be applicable.

**Comment by playXE** [comment] 2023-08-02 05:38
`&dyn Trait` can be replaced with AtomicU128. The problem is most likely in HashMap, it has to be replaced with DashMap to allow safe concurrent access

**Comment by k-sareen** [comment] 2023-08-06 12:58
A fix was merged in #879, but I'm keeping this issue open since removing `unsafe` would be ideal.

**Comment by qinsoon** [comment] 2023-09-06 01:03
Done in https://github.com/mmtk/mmtk-core/pull/931.

**Closed by qinsoon** 2023-09-06 01:03 UTC
